name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '.github/graphics/**'
      - '!.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
  init:
    name: Initialize
    permissions:
      contents: read
      pull-requests: read
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-24.04
    steps:
      # Get PR number for squash merges to main
      - id: pr
        uses: bcgov/action-get-pr@28b0adf8e4d40720d41f9c87356ce24b0a4bd6af # v0.3.1
  deploy-dev:
    name: DEV Deploys (${{ needs.init.outputs.pr }})
    needs: [init]
    uses: ./.github/workflows/reusable-deploy.yml
    secrets:
      db_password: ${{ secrets.db_password }}
      oc_namespace: ${{ secrets.oc_namespace }}
      oc_token: ${{ secrets.oc_token }}
    with:
      environment: dev
      target: dev
      tag: ${{ needs.init.outputs.pr }}

  tests:
    name: Tests
    needs: [deploy-dev]
    uses: ./.github/workflows/reusable-tests.yml
    with:
      target: dev
